version: '3.4'

services:
  products.complevo.presentation:
    image: products-complevo-presentation 
    build:
      context: .
      dockerfile: Products.Complevo.Presentation/Dockerfile
    depends_on:
      - sql-database

  sql-database:
    container_name: products-complevo-sql
    image: "mcr.microsoft.com/mssql/server:2017-latest" 
    ports:
      - 1433:1433
    environment:
      HEAP_NEWSIZE: 2500M
      MAX_HEAP_SIZE: 2596m
      SA_PASSWORD: 'Sql_p4ssword'
      MSSQL_SA_PASSWORD: 'Sql_p4ssword'
      ACCEPT_EULA: 'Y' 